/**
 * Verity Protocol - Global Tax Jurisdictions Database
 * Comprehensive tax rules for 200+ countries
 * 
 * NOTE: Tax rates are simplified representations. Actual rates may vary based on:
 * - Income brackets
 * - Filing status
 * - Special exemptions
 * - Treaty benefits
 * - Local regulations
 * 
 * Always consult with qualified tax professionals for specific advice.
 */

export interface JurisdictionRules {
  code: string;
  name: string;
  region: string;
  shortTermRate: number;
  longTermRate: number;
  longTermThresholdDays: number;
  dividendRate: number;
  cryptoSpecificRules?: {
    holdingPeriodExemption?: boolean;
    exemptionDays?: number;
    professionalTraderRules?: boolean;
    miningTaxed?: boolean;
    stakingTaxed?: boolean;
    airdropTaxed?: boolean;
    defiTaxed?: boolean;
    nftTaxed?: boolean;
    washSaleRule?: boolean;
    specificIdAllowed?: boolean;
  };
  treatyPartners: string[];
  currency: string;
  notes?: string;
}

// Comprehensive jurisdiction database with 200+ countries
export const JURISDICTION_RULES: Map<string, JurisdictionRules> = new Map([
  // =====================================================
  // NORTH AMERICA
  // =====================================================
  ['US', {
    code: 'US',
    name: 'United States',
    region: 'North America',
    shortTermRate: 37,
    longTermRate: 20,
    longTermThresholdDays: 365,
    dividendRate: 20,
    cryptoSpecificRules: {
      miningTaxed: true,
      stakingTaxed: true,
      airdropTaxed: true,
      defiTaxed: true,
      nftTaxed: true,
      washSaleRule: false, // Currently no wash sale for crypto
      specificIdAllowed: true,
    },
    treatyPartners: ['GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'NZ', 'KR', 'MX', 'SG', 'IL', 'IN', 'ZA', 'PL', 'CZ'],
    currency: 'USD',
    notes: 'IRS treats crypto as property. Form 8949 required.',
  }],
  ['CA', {
    code: 'CA',
    name: 'Canada',
    region: 'North America',
    shortTermRate: 33,
    longTermRate: 16.5, // 50% inclusion rate
    longTermThresholdDays: 0,
    dividendRate: 39.34,
    cryptoSpecificRules: {
      miningTaxed: true,
      stakingTaxed: true,
      airdropTaxed: true,
      specificIdAllowed: true,
    },
    treatyPartners: ['US', 'GB', 'DE', 'FR', 'JP', 'AU', 'NZ', 'CH', 'IT', 'ES', 'NL', 'BE', 'SE', 'NO', 'DK', 'IE', 'AT', 'KR', 'MX', 'SG', 'IL', 'IN', 'ZA'],
    currency: 'CAD',
    notes: '50% inclusion rate for capital gains.',
  }],
  ['MX', {
    code: 'MX',
    name: 'Mexico',
    region: 'North America',
    shortTermRate: 35,
    longTermRate: 35,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['US', 'CA', 'GB', 'DE', 'FR', 'ES', 'IT', 'JP', 'NL', 'BE', 'CH', 'SE', 'NO', 'DK', 'KR', 'AU', 'BR', 'CL', 'CO', 'AR'],
    currency: 'MXN',
  }],

  // =====================================================
  // EUROPE - WESTERN
  // =====================================================
  ['GB', {
    code: 'GB',
    name: 'United Kingdom',
    region: 'Europe',
    shortTermRate: 20,
    longTermRate: 20,
    longTermThresholdDays: 0,
    dividendRate: 33.75,
    cryptoSpecificRules: {
      miningTaxed: true,
      stakingTaxed: true,
      airdropTaxed: true,
      washSaleRule: true, // 30-day bed and breakfast rule
    },
    treatyPartners: ['US', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'NZ', 'KR', 'SG', 'IL', 'IN', 'ZA', 'PL', 'CZ', 'AE'],
    currency: 'GBP',
    notes: 'CGT allowance applies. DeFi earnings may be income.',
  }],
  ['DE', {
    code: 'DE',
    name: 'Germany',
    region: 'Europe',
    shortTermRate: 45,
    longTermRate: 0,
    longTermThresholdDays: 365,
    dividendRate: 26.375,
    cryptoSpecificRules: {
      holdingPeriodExemption: true,
      exemptionDays: 365,
      stakingTaxed: true,
      professionalTraderRules: true,
    },
    treatyPartners: ['US', 'GB', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'NZ', 'KR', 'SG', 'IL', 'IN', 'ZA', 'PL', 'CZ', 'AE'],
    currency: 'EUR',
    notes: 'Tax-free if held > 1 year. Staking extends to 10 years.',
  }],
  ['FR', {
    code: 'FR',
    name: 'France',
    region: 'Europe',
    shortTermRate: 30,
    longTermRate: 30,
    longTermThresholdDays: 0,
    dividendRate: 30,
    cryptoSpecificRules: {
      miningTaxed: true,
      stakingTaxed: true,
      professionalTraderRules: true,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'NZ', 'KR', 'SG', 'IL', 'IN', 'ZA', 'PL', 'CZ'],
    currency: 'EUR',
    notes: 'Flat 30% tax (PFU). Occasional vs professional distinction.',
  }],
  ['NL', {
    code: 'NL',
    name: 'Netherlands',
    region: 'Europe',
    shortTermRate: 32,
    longTermRate: 32,
    longTermThresholdDays: 0,
    dividendRate: 15,
    cryptoSpecificRules: {
      miningTaxed: true,
      stakingTaxed: true,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'NZ', 'KR', 'SG', 'IL', 'IN', 'ZA', 'PL', 'CZ'],
    currency: 'EUR',
    notes: 'Box 3 wealth tax on assets. Moving to actual returns.',
  }],
  ['BE', {
    code: 'BE',
    name: 'Belgium',
    region: 'Europe',
    shortTermRate: 33,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 30,
    cryptoSpecificRules: {
      professionalTraderRules: true,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'AT', 'NZ', 'KR', 'SG'],
    currency: 'EUR',
    notes: 'Generally tax-free for individuals (good management).',
  }],
  ['LU', {
    code: 'LU',
    name: 'Luxembourg',
    region: 'Europe',
    shortTermRate: 42,
    longTermRate: 0,
    longTermThresholdDays: 182,
    dividendRate: 15,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT'],
    currency: 'EUR',
    notes: 'Tax-free after 6 months holding.',
  }],
  ['CH', {
    code: 'CH',
    name: 'Switzerland',
    region: 'Europe',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 35,
    cryptoSpecificRules: {
      professionalTraderRules: true,
      miningTaxed: true,
      stakingTaxed: true,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'ES', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'NZ', 'KR', 'SG', 'IL', 'IN'],
    currency: 'CHF',
    notes: 'Tax-free for private investors. Wealth tax applies.',
  }],
  ['AT', {
    code: 'AT',
    name: 'Austria',
    region: 'Europe',
    shortTermRate: 27.5,
    longTermRate: 27.5,
    longTermThresholdDays: 0,
    dividendRate: 27.5,
    cryptoSpecificRules: {
      stakingTaxed: true,
      miningTaxed: true,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'NZ', 'KR', 'SG'],
    currency: 'EUR',
    notes: 'Flat 27.5% special tax rate for crypto.',
  }],
  ['IE', {
    code: 'IE',
    name: 'Ireland',
    region: 'Europe',
    shortTermRate: 33,
    longTermRate: 33,
    longTermThresholdDays: 0,
    dividendRate: 25,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'BE', 'AT', 'NZ', 'KR', 'SG'],
    currency: 'EUR',
    notes: 'CGT at 33%. Self-assessment required.',
  }],
  ['IT', {
    code: 'IT',
    name: 'Italy',
    region: 'Europe',
    shortTermRate: 26,
    longTermRate: 26,
    longTermThresholdDays: 0,
    dividendRate: 26,
    cryptoSpecificRules: {
      stakingTaxed: true,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'NZ', 'KR', 'SG'],
    currency: 'EUR',
    notes: '26% flat rate. Threshold of 51,645 EUR applies.',
  }],
  ['ES', {
    code: 'ES',
    name: 'Spain',
    region: 'Europe',
    shortTermRate: 26,
    longTermRate: 26,
    longTermThresholdDays: 0,
    dividendRate: 26,
    cryptoSpecificRules: {
      miningTaxed: true,
      stakingTaxed: true,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'NZ', 'KR', 'MX', 'BR', 'AR', 'CL', 'CO'],
    currency: 'EUR',
    notes: 'Progressive rates 19-26%. Modelo 720 for foreign assets.',
  }],
  ['PT', {
    code: 'PT',
    name: 'Portugal',
    region: 'Europe',
    shortTermRate: 28,
    longTermRate: 28,
    longTermThresholdDays: 365,
    dividendRate: 28,
    cryptoSpecificRules: {
      holdingPeriodExemption: true,
      exemptionDays: 365,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'BR'],
    currency: 'EUR',
    notes: 'Crypto held > 1 year is tax-free (as of 2023).',
  }],

  // =====================================================
  // EUROPE - NORTHERN
  // =====================================================
  ['SE', {
    code: 'SE',
    name: 'Sweden',
    region: 'Europe',
    shortTermRate: 30,
    longTermRate: 30,
    longTermThresholdDays: 0,
    dividendRate: 30,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'ES', 'CH', 'NO', 'DK', 'IE', 'BE', 'AT', 'NZ', 'KR', 'SG', 'FI'],
    currency: 'SEK',
    notes: 'Flat 30% on capital income.',
  }],
  ['NO', {
    code: 'NO',
    name: 'Norway',
    region: 'Europe',
    shortTermRate: 22,
    longTermRate: 22,
    longTermThresholdDays: 0,
    dividendRate: 35.2,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'DK', 'IE', 'BE', 'AT', 'NZ', 'KR', 'SG', 'FI'],
    currency: 'NOK',
    notes: '22% on net gains. Wealth tax on assets.',
  }],
  ['DK', {
    code: 'DK',
    name: 'Denmark',
    region: 'Europe',
    shortTermRate: 42,
    longTermRate: 42,
    longTermThresholdDays: 0,
    dividendRate: 42,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'IE', 'BE', 'AT', 'NZ', 'KR', 'SG', 'FI'],
    currency: 'DKK',
    notes: 'High rates. Stock income taxation rules apply.',
  }],
  ['FI', {
    code: 'FI',
    name: 'Finland',
    region: 'Europe',
    shortTermRate: 34,
    longTermRate: 34,
    longTermThresholdDays: 0,
    dividendRate: 25.5,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'NZ', 'KR', 'SG', 'EE'],
    currency: 'EUR',
    notes: '30-34% progressive capital gains tax.',
  }],
  ['IS', {
    code: 'IS',
    name: 'Iceland',
    region: 'Europe',
    shortTermRate: 22,
    longTermRate: 22,
    longTermThresholdDays: 0,
    dividendRate: 22,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'FR', 'NL', 'SE', 'NO', 'DK', 'FI'],
    currency: 'ISK',
    notes: 'Flat 22% on capital gains.',
  }],
  ['EE', {
    code: 'EE',
    name: 'Estonia',
    region: 'Europe',
    shortTermRate: 20,
    longTermRate: 20,
    longTermThresholdDays: 0,
    dividendRate: 20,
    cryptoSpecificRules: {
      miningTaxed: true,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'FR', 'NL', 'SE', 'NO', 'DK', 'FI', 'LV', 'LT'],
    currency: 'EUR',
    notes: 'Favorable e-residency program.',
  }],
  ['LV', {
    code: 'LV',
    name: 'Latvia',
    region: 'Europe',
    shortTermRate: 20,
    longTermRate: 20,
    longTermThresholdDays: 0,
    dividendRate: 20,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'FR', 'NL', 'SE', 'NO', 'DK', 'FI', 'EE', 'LT'],
    currency: 'EUR',
  }],
  ['LT', {
    code: 'LT',
    name: 'Lithuania',
    region: 'Europe',
    shortTermRate: 15,
    longTermRate: 15,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'FR', 'NL', 'SE', 'NO', 'DK', 'FI', 'EE', 'LV'],
    currency: 'EUR',
    notes: 'Low 15% flat rate.',
  }],

  // =====================================================
  // EUROPE - EASTERN & CENTRAL
  // =====================================================
  ['PL', {
    code: 'PL',
    name: 'Poland',
    region: 'Europe',
    shortTermRate: 19,
    longTermRate: 19,
    longTermThresholdDays: 0,
    dividendRate: 19,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'CZ', 'SK', 'HU'],
    currency: 'PLN',
    notes: 'Flat 19% on capital gains.',
  }],
  ['CZ', {
    code: 'CZ',
    name: 'Czech Republic',
    region: 'Europe',
    shortTermRate: 15,
    longTermRate: 0,
    longTermThresholdDays: 1095,
    dividendRate: 15,
    cryptoSpecificRules: {
      holdingPeriodExemption: true,
      exemptionDays: 1095,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'PL', 'SK', 'HU'],
    currency: 'CZK',
    notes: 'Tax-free after 3 years holding.',
  }],
  ['SK', {
    code: 'SK',
    name: 'Slovakia',
    region: 'Europe',
    shortTermRate: 19,
    longTermRate: 19,
    longTermThresholdDays: 0,
    dividendRate: 7,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'PL', 'CZ', 'HU'],
    currency: 'EUR',
  }],
  ['HU', {
    code: 'HU',
    name: 'Hungary',
    region: 'Europe',
    shortTermRate: 15,
    longTermRate: 15,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'PL', 'CZ', 'SK'],
    currency: 'HUF',
    notes: 'Flat 15% personal income tax.',
  }],
  ['RO', {
    code: 'RO',
    name: 'Romania',
    region: 'Europe',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 8,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'PL', 'CZ', 'HU', 'BG'],
    currency: 'RON',
    notes: 'Low 10% flat rate.',
  }],
  ['BG', {
    code: 'BG',
    name: 'Bulgaria',
    region: 'Europe',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 5,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'PL', 'CZ', 'HU', 'RO'],
    currency: 'BGN',
    notes: 'Flat 10% - one of lowest in EU.',
  }],
  ['HR', {
    code: 'HR',
    name: 'Croatia',
    region: 'Europe',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 730,
    dividendRate: 10,
    cryptoSpecificRules: {
      holdingPeriodExemption: true,
      exemptionDays: 730,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'SI'],
    currency: 'EUR',
    notes: 'Tax-free after 2 years.',
  }],
  ['SI', {
    code: 'SI',
    name: 'Slovenia',
    region: 'Europe',
    shortTermRate: 25,
    longTermRate: 0,
    longTermThresholdDays: 7300,
    dividendRate: 25,
    cryptoSpecificRules: {
      holdingPeriodExemption: true,
      exemptionDays: 7300,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'HR'],
    currency: 'EUR',
    notes: 'Tax decreases with holding period. 0% after 20 years.',
  }],
  ['GR', {
    code: 'GR',
    name: 'Greece',
    region: 'Europe',
    shortTermRate: 15,
    longTermRate: 15,
    longTermThresholdDays: 0,
    dividendRate: 5,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'CY'],
    currency: 'EUR',
    notes: '15% on capital gains.',
  }],
  ['CY', {
    code: 'CY',
    name: 'Cyprus',
    region: 'Europe',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'GR', 'RU'],
    currency: 'EUR',
    notes: 'No capital gains tax on securities.',
  }],
  ['MT', {
    code: 'MT',
    name: 'Malta',
    region: 'Europe',
    shortTermRate: 35,
    longTermRate: 35,
    longTermThresholdDays: 0,
    dividendRate: 15,
    cryptoSpecificRules: {
      miningTaxed: true,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'AE'],
    currency: 'EUR',
    notes: 'DLT regulatory framework. High nominal rate.',
  }],
  ['RU', {
    code: 'RU',
    name: 'Russia',
    region: 'Europe',
    shortTermRate: 13,
    longTermRate: 13,
    longTermThresholdDays: 0,
    dividendRate: 13,
    treatyPartners: ['DE', 'FR', 'IT', 'ES', 'CH', 'CY', 'CN', 'IN', 'JP', 'KR'],
    currency: 'RUB',
    notes: 'Flat 13% tax. Crypto legalized 2021.',
  }],
  ['UA', {
    code: 'UA',
    name: 'Ukraine',
    region: 'Europe',
    shortTermRate: 18,
    longTermRate: 18,
    longTermThresholdDays: 0,
    dividendRate: 9,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'PL'],
    currency: 'UAH',
    notes: 'Crypto legalized 2022.',
  }],

  // =====================================================
  // ASIA-PACIFIC
  // =====================================================
  ['JP', {
    code: 'JP',
    name: 'Japan',
    region: 'Asia-Pacific',
    shortTermRate: 55,
    longTermRate: 55,
    longTermThresholdDays: 0,
    dividendRate: 20.315,
    cryptoSpecificRules: {
      miningTaxed: true,
      stakingTaxed: true,
      airdropTaxed: true,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'AU', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'NZ', 'KR', 'SG', 'IN', 'CN'],
    currency: 'JPY',
    notes: 'Crypto taxed as miscellaneous income up to 55%.',
  }],
  ['KR', {
    code: 'KR',
    name: 'South Korea',
    region: 'Asia-Pacific',
    shortTermRate: 22,
    longTermRate: 22,
    longTermThresholdDays: 0,
    dividendRate: 15.4,
    cryptoSpecificRules: {
      miningTaxed: true,
      stakingTaxed: true,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'SG', 'IN', 'CN'],
    currency: 'KRW',
    notes: '22% on gains > 2.5M KRW (delayed implementation).',
  }],
  ['CN', {
    code: 'CN',
    name: 'China',
    region: 'Asia-Pacific',
    shortTermRate: 20,
    longTermRate: 20,
    longTermThresholdDays: 0,
    dividendRate: 20,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'KR', 'SG', 'IN'],
    currency: 'CNY',
    notes: 'Crypto trading banned. Tax unclear.',
  }],
  ['HK', {
    code: 'HK',
    name: 'Hong Kong',
    region: 'Asia-Pacific',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB', 'BE', 'NL', 'LU', 'CH', 'IE', 'AU', 'NZ', 'TH', 'MY', 'VN', 'ID'],
    currency: 'HKD',
    notes: 'No capital gains tax. Territorial taxation.',
  }],
  ['SG', {
    code: 'SG',
    name: 'Singapore',
    region: 'Asia-Pacific',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'KR', 'IN', 'CN', 'MY', 'TH', 'ID', 'VN'],
    currency: 'SGD',
    notes: 'No capital gains tax. Crypto-friendly jurisdiction.',
  }],
  ['MY', {
    code: 'MY',
    name: 'Malaysia',
    region: 'Asia-Pacific',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'CH', 'SG', 'TH', 'ID', 'VN', 'IN', 'CN'],
    currency: 'MYR',
    notes: 'No capital gains tax on crypto.',
  }],
  ['TH', {
    code: 'TH',
    name: 'Thailand',
    region: 'Asia-Pacific',
    shortTermRate: 15,
    longTermRate: 15,
    longTermThresholdDays: 0,
    dividendRate: 10,
    cryptoSpecificRules: {
      miningTaxed: true,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'CH', 'SG', 'MY', 'ID', 'VN', 'IN', 'CN', 'KR'],
    currency: 'THB',
    notes: '15% WHT on crypto gains.',
  }],
  ['ID', {
    code: 'ID',
    name: 'Indonesia',
    region: 'Asia-Pacific',
    shortTermRate: 0.1,
    longTermRate: 0.1,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'CH', 'SG', 'MY', 'TH', 'VN', 'IN', 'CN', 'KR'],
    currency: 'IDR',
    notes: '0.1% on crypto sales + 0.1% income tax.',
  }],
  ['VN', {
    code: 'VN',
    name: 'Vietnam',
    region: 'Asia-Pacific',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'CH', 'SG', 'MY', 'TH', 'ID', 'IN', 'CN', 'KR'],
    currency: 'VND',
    notes: 'Crypto unregulated. No tax framework yet.',
  }],
  ['PH', {
    code: 'PH',
    name: 'Philippines',
    region: 'Asia-Pacific',
    shortTermRate: 15,
    longTermRate: 15,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'CH', 'SG', 'MY', 'TH', 'ID', 'IN', 'CN', 'KR'],
    currency: 'PHP',
    notes: '15% on capital gains.',
  }],
  ['IN', {
    code: 'IN',
    name: 'India',
    region: 'Asia-Pacific',
    shortTermRate: 30,
    longTermRate: 30,
    longTermThresholdDays: 0,
    dividendRate: 20,
    cryptoSpecificRules: {
      miningTaxed: true,
      stakingTaxed: true,
      airdropTaxed: true,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'CH', 'SG', 'MY', 'TH', 'AE', 'CN', 'KR'],
    currency: 'INR',
    notes: 'Flat 30% on crypto. 1% TDS on transfers.',
  }],
  ['AU', {
    code: 'AU',
    name: 'Australia',
    region: 'Asia-Pacific',
    shortTermRate: 45,
    longTermRate: 22.5,
    longTermThresholdDays: 365,
    dividendRate: 30,
    cryptoSpecificRules: {
      miningTaxed: true,
      stakingTaxed: true,
      airdropTaxed: true,
      specificIdAllowed: true,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'NZ', 'KR', 'SG', 'IN', 'CN', 'HK'],
    currency: 'AUD',
    notes: '50% discount for assets held > 1 year.',
  }],
  ['NZ', {
    code: 'NZ',
    name: 'New Zealand',
    region: 'Asia-Pacific',
    shortTermRate: 39,
    longTermRate: 39,
    longTermThresholdDays: 0,
    dividendRate: 33,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'CH', 'SE', 'NO', 'DK', 'IE', 'SG', 'KR', 'HK'],
    currency: 'NZD',
    notes: 'Taxed if purchased with intent to sell.',
  }],
  ['TW', {
    code: 'TW',
    name: 'Taiwan',
    region: 'Asia-Pacific',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: [],
    currency: 'TWD',
    notes: 'No capital gains tax for individuals.',
  }],
  ['PK', {
    code: 'PK',
    name: 'Pakistan',
    region: 'Asia-Pacific',
    shortTermRate: 15,
    longTermRate: 15,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'FR', 'CH', 'MY', 'SG', 'AE', 'SA', 'CN'],
    currency: 'PKR',
    notes: 'Crypto taxed as capital gains.',
  }],
  ['BD', {
    code: 'BD',
    name: 'Bangladesh',
    region: 'Asia-Pacific',
    shortTermRate: 15,
    longTermRate: 15,
    longTermThresholdDays: 0,
    dividendRate: 20,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'FR', 'MY', 'SG', 'IN', 'CN', 'AE'],
    currency: 'BDT',
  }],
  ['LK', {
    code: 'LK',
    name: 'Sri Lanka',
    region: 'Asia-Pacific',
    shortTermRate: 14,
    longTermRate: 14,
    longTermThresholdDays: 0,
    dividendRate: 14,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'FR', 'MY', 'SG', 'IN', 'CN', 'AE', 'AU'],
    currency: 'LKR',
  }],

  // =====================================================
  // MIDDLE EAST
  // =====================================================
  ['AE', {
    code: 'AE',
    name: 'United Arab Emirates',
    region: 'Middle East',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB', 'DE', 'FR', 'NL', 'IT', 'ES', 'CH', 'IN', 'CN', 'PK', 'EG', 'SA'],
    currency: 'AED',
    notes: 'No income/capital gains tax. Popular for crypto.',
  }],
  ['SA', {
    code: 'SA',
    name: 'Saudi Arabia',
    region: 'Middle East',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB', 'DE', 'FR', 'NL', 'IT', 'ES', 'CH', 'IN', 'CN', 'PK', 'EG', 'AE', 'JP', 'KR'],
    currency: 'SAR',
    notes: 'No personal income tax. Crypto uncertain.',
  }],
  ['IL', {
    code: 'IL',
    name: 'Israel',
    region: 'Middle East',
    shortTermRate: 25,
    longTermRate: 25,
    longTermThresholdDays: 0,
    dividendRate: 25,
    cryptoSpecificRules: {
      miningTaxed: true,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'IE', 'BE', 'AT', 'KR', 'SG', 'IN'],
    currency: 'ILS',
    notes: '25% on capital gains. Crypto is property.',
  }],
  ['QA', {
    code: 'QA',
    name: 'Qatar',
    region: 'Middle East',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB', 'FR', 'CH', 'IN', 'CN', 'SG', 'KR'],
    currency: 'QAR',
    notes: 'No personal income tax.',
  }],
  ['KW', {
    code: 'KW',
    name: 'Kuwait',
    region: 'Middle East',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB', 'FR', 'CH', 'IN', 'CN', 'SG'],
    currency: 'KWD',
    notes: 'No personal income tax.',
  }],
  ['BH', {
    code: 'BH',
    name: 'Bahrain',
    region: 'Middle East',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB', 'FR', 'CH', 'MY', 'SG'],
    currency: 'BHD',
    notes: 'No personal income tax. Crypto-friendly.',
  }],
  ['OM', {
    code: 'OM',
    name: 'Oman',
    region: 'Middle East',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB', 'FR', 'CH', 'IN', 'CN'],
    currency: 'OMR',
    notes: 'No personal income tax.',
  }],
  ['JO', {
    code: 'JO',
    name: 'Jordan',
    region: 'Middle East',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB', 'FR', 'CH', 'IN', 'EG', 'AE'],
    currency: 'JOD',
    notes: 'No capital gains tax.',
  }],
  ['LB', {
    code: 'LB',
    name: 'Lebanon',
    region: 'Middle East',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['FR', 'IT', 'EG', 'JO', 'SY'],
    currency: 'LBP',
  }],
  ['TR', {
    code: 'TR',
    name: 'Turkey',
    region: 'Middle East',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'DK', 'AE', 'SA'],
    currency: 'TRY',
    notes: 'No capital gains tax for individuals.',
  }],

  // =====================================================
  // AFRICA
  // =====================================================
  ['ZA', {
    code: 'ZA',
    name: 'South Africa',
    region: 'Africa',
    shortTermRate: 45,
    longTermRate: 18,
    longTermThresholdDays: 1095,
    dividendRate: 20,
    cryptoSpecificRules: {
      miningTaxed: true,
      stakingTaxed: true,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'NL', 'IT', 'ES', 'CH', 'SE', 'NO', 'IE', 'IN', 'CN', 'KR'],
    currency: 'ZAR',
    notes: 'CGT at effective 18%. Crypto is financial instrument.',
  }],
  ['EG', {
    code: 'EG',
    name: 'Egypt',
    region: 'Africa',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['US', 'GB', 'DE', 'FR', 'IT', 'CH', 'IN', 'CN', 'AE', 'SA', 'JO'],
    currency: 'EGP',
    notes: 'No capital gains tax on stocks.',
  }],
  ['NG', {
    code: 'NG',
    name: 'Nigeria',
    region: 'Africa',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['GB', 'CA', 'FR', 'NL', 'BE', 'ZA', 'CN'],
    currency: 'NGN',
    notes: '10% CGT. High crypto adoption.',
  }],
  ['KE', {
    code: 'KE',
    name: 'Kenya',
    region: 'Africa',
    shortTermRate: 5,
    longTermRate: 5,
    longTermThresholdDays: 0,
    dividendRate: 5,
    treatyPartners: ['GB', 'DE', 'FR', 'CA', 'IN', 'ZA'],
    currency: 'KES',
    notes: '5% CGT. Crypto unregulated.',
  }],
  ['GH', {
    code: 'GH',
    name: 'Ghana',
    region: 'Africa',
    shortTermRate: 15,
    longTermRate: 15,
    longTermThresholdDays: 0,
    dividendRate: 8,
    treatyPartners: ['GB', 'DE', 'FR', 'ZA'],
    currency: 'GHS',
  }],
  ['MA', {
    code: 'MA',
    name: 'Morocco',
    region: 'Africa',
    shortTermRate: 20,
    longTermRate: 20,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['FR', 'ES', 'IT', 'BE', 'NL', 'CH', 'AE'],
    currency: 'MAD',
    notes: 'Crypto banned but regulations evolving.',
  }],
  ['TN', {
    code: 'TN',
    name: 'Tunisia',
    region: 'Africa',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['FR', 'IT', 'DE', 'BE', 'NL', 'CH'],
    currency: 'TND',
  }],
  ['TZ', {
    code: 'TZ',
    name: 'Tanzania',
    region: 'Africa',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['GB', 'DE', 'SE', 'NO', 'DK', 'ZA', 'IN'],
    currency: 'TZS',
  }],
  ['UG', {
    code: 'UG',
    name: 'Uganda',
    region: 'Africa',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['GB', 'NL', 'NO', 'DK', 'ZA', 'IN'],
    currency: 'UGX',
    notes: 'No capital gains tax for individuals.',
  }],
  ['RW', {
    code: 'RW',
    name: 'Rwanda',
    region: 'Africa',
    shortTermRate: 5,
    longTermRate: 5,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['BE', 'ZA'],
    currency: 'RWF',
    notes: 'Low 5% CGT.',
  }],
  ['MU', {
    code: 'MU',
    name: 'Mauritius',
    region: 'Africa',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB', 'FR', 'DE', 'IN', 'CN', 'ZA', 'SG', 'MY', 'AE'],
    currency: 'MUR',
    notes: 'No capital gains tax. Popular offshore hub.',
  }],
  ['SC', {
    code: 'SC',
    name: 'Seychelles',
    region: 'Africa',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB', 'FR', 'AE', 'CN', 'IN', 'ZA'],
    currency: 'SCR',
    notes: 'No capital gains tax.',
  }],

  // =====================================================
  // LATIN AMERICA & CARIBBEAN
  // =====================================================
  ['BR', {
    code: 'BR',
    name: 'Brazil',
    region: 'Latin America',
    shortTermRate: 22.5,
    longTermRate: 15,
    longTermThresholdDays: 0,
    dividendRate: 0,
    cryptoSpecificRules: {
      miningTaxed: true,
    },
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'FR', 'NL', 'IT', 'ES', 'PT', 'MX', 'AR', 'CL'],
    currency: 'BRL',
    notes: '15-22.5% progressive rates. No dividend tax.',
  }],
  ['AR', {
    code: 'AR',
    name: 'Argentina',
    region: 'Latin America',
    shortTermRate: 15,
    longTermRate: 15,
    longTermThresholdDays: 0,
    dividendRate: 7,
    treatyPartners: ['US', 'GB', 'DE', 'FR', 'ES', 'IT', 'BR', 'CL', 'MX'],
    currency: 'ARS',
    notes: '15% CGT. High crypto adoption.',
  }],
  ['CL', {
    code: 'CL',
    name: 'Chile',
    region: 'Latin America',
    shortTermRate: 40,
    longTermRate: 40,
    longTermThresholdDays: 0,
    dividendRate: 35,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'JP', 'AU', 'FR', 'ES', 'IT', 'BR', 'AR', 'MX', 'KR'],
    currency: 'CLP',
    notes: 'High rates. Taxed as Global Complementary.',
  }],
  ['CO', {
    code: 'CO',
    name: 'Colombia',
    region: 'Latin America',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 730,
    dividendRate: 10,
    treatyPartners: ['US', 'GB', 'DE', 'CA', 'FR', 'ES', 'IT', 'MX', 'CL', 'KR'],
    currency: 'COP',
    notes: '10% CGT after 2 years.',
  }],
  ['PE', {
    code: 'PE',
    name: 'Peru',
    region: 'Latin America',
    shortTermRate: 5,
    longTermRate: 5,
    longTermThresholdDays: 0,
    dividendRate: 5,
    treatyPartners: ['US', 'CA', 'BR', 'CL', 'MX', 'KR', 'CH'],
    currency: 'PEN',
    notes: 'Low 5% CGT.',
  }],
  ['EC', {
    code: 'EC',
    name: 'Ecuador',
    region: 'Latin America',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['DE', 'FR', 'ES', 'IT', 'MX', 'BR', 'CL'],
    currency: 'USD',
    notes: 'Uses USD. Crypto regulations developing.',
  }],
  ['VE', {
    code: 'VE',
    name: 'Venezuela',
    region: 'Latin America',
    shortTermRate: 34,
    longTermRate: 34,
    longTermThresholdDays: 0,
    dividendRate: 34,
    treatyPartners: ['ES', 'IT', 'FR', 'PT', 'BR'],
    currency: 'VES',
    notes: 'High rates. Petro cryptocurrency.',
  }],
  ['UY', {
    code: 'UY',
    name: 'Uruguay',
    region: 'Latin America',
    shortTermRate: 12,
    longTermRate: 12,
    longTermThresholdDays: 0,
    dividendRate: 7,
    treatyPartners: ['DE', 'ES', 'FR', 'HU', 'KR', 'MX', 'AR'],
    currency: 'UYU',
    notes: '12% on foreign source capital gains.',
  }],
  ['PY', {
    code: 'PY',
    name: 'Paraguay',
    region: 'Latin America',
    shortTermRate: 8,
    longTermRate: 8,
    longTermThresholdDays: 0,
    dividendRate: 8,
    treatyPartners: ['AR', 'BR', 'CL', 'UY'],
    currency: 'PYG',
    notes: 'Low 8% flat rate. Crypto mining hub.',
  }],
  ['BO', {
    code: 'BO',
    name: 'Bolivia',
    region: 'Latin America',
    shortTermRate: 13,
    longTermRate: 13,
    longTermThresholdDays: 0,
    dividendRate: 12.5,
    treatyPartners: ['DE', 'FR', 'ES', 'AR', 'BR', 'CL'],
    currency: 'BOB',
  }],
  ['PA', {
    code: 'PA',
    name: 'Panama',
    region: 'Latin America',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 5,
    treatyPartners: ['US', 'GB', 'ES', 'NL', 'MX', 'AE', 'SG', 'KR'],
    currency: 'PAB',
    notes: 'Territorial taxation. Crypto-friendly.',
  }],
  ['CR', {
    code: 'CR',
    name: 'Costa Rica',
    region: 'Latin America',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['DE', 'ES'],
    currency: 'CRC',
    notes: 'Territorial taxation. No CGT.',
  }],
  ['GT', {
    code: 'GT',
    name: 'Guatemala',
    region: 'Latin America',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 5,
    treatyPartners: [],
    currency: 'GTQ',
  }],
  ['HN', {
    code: 'HN',
    name: 'Honduras',
    region: 'Latin America',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['ES'],
    currency: 'HNL',
  }],
  ['SV', {
    code: 'SV',
    name: 'El Salvador',
    region: 'Latin America',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 5,
    cryptoSpecificRules: {
      miningTaxed: false,
      stakingTaxed: false,
    },
    treatyPartners: ['ES'],
    currency: 'USD',
    notes: 'Bitcoin legal tender. Crypto gains exempt.',
  }],
  ['NI', {
    code: 'NI',
    name: 'Nicaragua',
    region: 'Latin America',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['ES'],
    currency: 'NIO',
  }],
  ['DO', {
    code: 'DO',
    name: 'Dominican Republic',
    region: 'Latin America',
    shortTermRate: 27,
    longTermRate: 27,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['US', 'CA', 'ES'],
    currency: 'DOP',
  }],
  ['JM', {
    code: 'JM',
    name: 'Jamaica',
    region: 'Caribbean',
    shortTermRate: 15,
    longTermRate: 15,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['US', 'GB', 'CA'],
    currency: 'JMD',
  }],
  ['TT', {
    code: 'TT',
    name: 'Trinidad and Tobago',
    region: 'Caribbean',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['US', 'GB', 'CA', 'DE', 'CH'],
    currency: 'TTD',
    notes: 'No capital gains tax.',
  }],
  ['BS', {
    code: 'BS',
    name: 'Bahamas',
    region: 'Caribbean',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB'],
    currency: 'BSD',
    notes: 'No income or capital gains tax.',
  }],
  ['BB', {
    code: 'BB',
    name: 'Barbados',
    region: 'Caribbean',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['US', 'GB', 'CA'],
    currency: 'BBD',
    notes: 'No capital gains tax.',
  }],
  ['KY', {
    code: 'KY',
    name: 'Cayman Islands',
    region: 'Caribbean',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB'],
    currency: 'KYD',
    notes: 'Tax haven. No direct taxes.',
  }],
  ['VG', {
    code: 'VG',
    name: 'British Virgin Islands',
    region: 'Caribbean',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB'],
    currency: 'USD',
    notes: 'Tax haven. No income taxes.',
  }],
  ['BM', {
    code: 'BM',
    name: 'Bermuda',
    region: 'Caribbean',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['US', 'GB'],
    currency: 'BMD',
    notes: 'No income tax. Crypto-friendly regulations.',
  }],
  ['PR', {
    code: 'PR',
    name: 'Puerto Rico',
    region: 'Caribbean',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    cryptoSpecificRules: {
      holdingPeriodExemption: true,
    },
    treatyPartners: ['US'],
    currency: 'USD',
    notes: 'Act 60 provides 0% CGT for residents.',
  }],

  // =====================================================
  // CENTRAL ASIA & CAUCASUS
  // =====================================================
  ['KZ', {
    code: 'KZ',
    name: 'Kazakhstan',
    region: 'Central Asia',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 5,
    treatyPartners: ['US', 'GB', 'DE', 'FR', 'CN', 'RU', 'TR'],
    currency: 'KZT',
    notes: 'Crypto mining hub. AIFC regulations.',
  }],
  ['UZ', {
    code: 'UZ',
    name: 'Uzbekistan',
    region: 'Central Asia',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 5,
    cryptoSpecificRules: {
      miningTaxed: false,
    },
    treatyPartners: ['GB', 'DE', 'FR', 'CN', 'RU', 'TR', 'KR'],
    currency: 'UZS',
    notes: 'Crypto tax exempt for individuals.',
  }],
  ['TM', {
    code: 'TM',
    name: 'Turkmenistan',
    region: 'Central Asia',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['RU', 'TR'],
    currency: 'TMT',
  }],
  ['KG', {
    code: 'KG',
    name: 'Kyrgyzstan',
    region: 'Central Asia',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['RU', 'CN', 'TR', 'DE', 'GB'],
    currency: 'KGS',
  }],
  ['TJ', {
    code: 'TJ',
    name: 'Tajikistan',
    region: 'Central Asia',
    shortTermRate: 12,
    longTermRate: 12,
    longTermThresholdDays: 0,
    dividendRate: 12,
    treatyPartners: ['RU', 'CN', 'TR'],
    currency: 'TJS',
  }],
  ['GE', {
    code: 'GE',
    name: 'Georgia',
    region: 'Caucasus',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 5,
    cryptoSpecificRules: {
      miningTaxed: false,
      stakingTaxed: false,
    },
    treatyPartners: ['US', 'GB', 'DE', 'FR', 'NL', 'TR', 'AE'],
    currency: 'GEL',
    notes: 'Crypto tax-free for individuals. Popular hub.',
  }],
  ['AM', {
    code: 'AM',
    name: 'Armenia',
    region: 'Caucasus',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 5,
    treatyPartners: ['RU', 'FR', 'DE', 'AE'],
    currency: 'AMD',
  }],
  ['AZ', {
    code: 'AZ',
    name: 'Azerbaijan',
    region: 'Caucasus',
    shortTermRate: 14,
    longTermRate: 14,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['RU', 'TR', 'DE', 'GB', 'AE'],
    currency: 'AZN',
  }],

  // =====================================================
  // OCEANIA (additional)
  // =====================================================
  ['FJ', {
    code: 'FJ',
    name: 'Fiji',
    region: 'Oceania',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 20,
    treatyPartners: ['AU', 'NZ', 'GB'],
    currency: 'FJD',
  }],
  ['PG', {
    code: 'PG',
    name: 'Papua New Guinea',
    region: 'Oceania',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 17,
    treatyPartners: ['AU', 'DE', 'GB', 'SG', 'MY'],
    currency: 'PGK',
    notes: 'No capital gains tax.',
  }],
  ['WS', {
    code: 'WS',
    name: 'Samoa',
    region: 'Oceania',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['NZ', 'AU'],
    currency: 'WST',
    notes: 'No capital gains tax.',
  }],
  ['VU', {
    code: 'VU',
    name: 'Vanuatu',
    region: 'Oceania',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: [],
    currency: 'VUV',
    notes: 'Tax haven. No income taxes.',
  }],

  // =====================================================
  // ADDITIONAL COUNTRIES
  // =====================================================
  ['MN', {
    code: 'MN',
    name: 'Mongolia',
    region: 'Asia',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['RU', 'CN', 'KR', 'DE', 'GB'],
    currency: 'MNT',
  }],
  ['NP', {
    code: 'NP',
    name: 'Nepal',
    region: 'Asia',
    shortTermRate: 7.5,
    longTermRate: 7.5,
    longTermThresholdDays: 0,
    dividendRate: 5,
    treatyPartners: ['IN', 'TH', 'CN'],
    currency: 'NPR',
  }],
  ['MM', {
    code: 'MM',
    name: 'Myanmar',
    region: 'Asia',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB', 'SG', 'MY', 'TH', 'IN'],
    currency: 'MMK',
  }],
  ['KH', {
    code: 'KH',
    name: 'Cambodia',
    region: 'Asia',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 14,
    treatyPartners: ['SG', 'TH', 'CN', 'KR'],
    currency: 'KHR',
    notes: 'No capital gains tax.',
  }],
  ['LA', {
    code: 'LA',
    name: 'Laos',
    region: 'Asia',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['TH', 'VN', 'CN', 'KR'],
    currency: 'LAK',
  }],
  ['BN', {
    code: 'BN',
    name: 'Brunei',
    region: 'Asia',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB', 'SG', 'MY', 'JP'],
    currency: 'BND',
    notes: 'No income or capital gains tax.',
  }],
  ['MV', {
    code: 'MV',
    name: 'Maldives',
    region: 'Asia',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: [],
    currency: 'MVR',
    notes: 'No income tax.',
  }],
  ['BT', {
    code: 'BT',
    name: 'Bhutan',
    region: 'Asia',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['IN'],
    currency: 'BTN',
  }],
  ['AF', {
    code: 'AF',
    name: 'Afghanistan',
    region: 'Asia',
    shortTermRate: 20,
    longTermRate: 20,
    longTermThresholdDays: 0,
    dividendRate: 20,
    treatyPartners: [],
    currency: 'AFN',
  }],
  ['IQ', {
    code: 'IQ',
    name: 'Iraq',
    region: 'Middle East',
    shortTermRate: 15,
    longTermRate: 15,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['FR', 'EG', 'JO'],
    currency: 'IQD',
  }],
  ['SY', {
    code: 'SY',
    name: 'Syria',
    region: 'Middle East',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 7.5,
    treatyPartners: ['FR', 'EG', 'JO', 'LB'],
    currency: 'SYP',
  }],
  ['YE', {
    code: 'YE',
    name: 'Yemen',
    region: 'Middle East',
    shortTermRate: 20,
    longTermRate: 20,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['EG', 'SA', 'AE'],
    currency: 'YER',
  }],
  ['DZ', {
    code: 'DZ',
    name: 'Algeria',
    region: 'Africa',
    shortTermRate: 15,
    longTermRate: 15,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['FR', 'BE', 'IT', 'ES', 'AE'],
    currency: 'DZD',
    notes: 'Crypto banned.',
  }],
  ['LY', {
    code: 'LY',
    name: 'Libya',
    region: 'Africa',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['EG', 'TN'],
    currency: 'LYD',
    notes: 'No income tax.',
  }],
  ['ET', {
    code: 'ET',
    name: 'Ethiopia',
    region: 'Africa',
    shortTermRate: 15,
    longTermRate: 15,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['GB', 'FR', 'IT', 'IN', 'CN'],
    currency: 'ETB',
  }],
  ['SD', {
    code: 'SD',
    name: 'Sudan',
    region: 'Africa',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['EG'],
    currency: 'SDG',
    notes: 'No capital gains tax.',
  }],
  ['AO', {
    code: 'AO',
    name: 'Angola',
    region: 'Africa',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['PT', 'AE'],
    currency: 'AOA',
  }],
  ['ZM', {
    code: 'ZM',
    name: 'Zambia',
    region: 'Africa',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['GB', 'ZA', 'DE', 'CA', 'NO'],
    currency: 'ZMW',
    notes: 'No capital gains tax.',
  }],
  ['ZW', {
    code: 'ZW',
    name: 'Zimbabwe',
    region: 'Africa',
    shortTermRate: 20,
    longTermRate: 20,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['ZA', 'GB', 'DE', 'CA'],
    currency: 'ZWL',
  }],
  ['BW', {
    code: 'BW',
    name: 'Botswana',
    region: 'Africa',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 7.5,
    treatyPartners: ['ZA', 'GB', 'SE', 'FR'],
    currency: 'BWP',
    notes: 'No capital gains tax.',
  }],
  ['NA', {
    code: 'NA',
    name: 'Namibia',
    region: 'Africa',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 20,
    treatyPartners: ['ZA', 'DE', 'FR'],
    currency: 'NAD',
    notes: 'No capital gains tax.',
  }],
  ['MZ', {
    code: 'MZ',
    name: 'Mozambique',
    region: 'Africa',
    shortTermRate: 32,
    longTermRate: 32,
    longTermThresholdDays: 0,
    dividendRate: 20,
    treatyPartners: ['PT', 'ZA', 'IT', 'AE'],
    currency: 'MZN',
  }],
  ['MG', {
    code: 'MG',
    name: 'Madagascar',
    region: 'Africa',
    shortTermRate: 20,
    longTermRate: 20,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['FR'],
    currency: 'MGA',
  }],
  ['SN', {
    code: 'SN',
    name: 'Senegal',
    region: 'Africa',
    shortTermRate: 5,
    longTermRate: 5,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['FR', 'BE', 'IT'],
    currency: 'XOF',
    notes: 'Low 5% CGT.',
  }],
  ['CI', {
    code: 'CI',
    name: 'Ivory Coast',
    region: 'Africa',
    shortTermRate: 12,
    longTermRate: 12,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['FR', 'DE', 'GB', 'BE'],
    currency: 'XOF',
  }],
  ['CM', {
    code: 'CM',
    name: 'Cameroon',
    region: 'Africa',
    shortTermRate: 16.5,
    longTermRate: 16.5,
    longTermThresholdDays: 0,
    dividendRate: 16.5,
    treatyPartners: ['FR', 'CA'],
    currency: 'XAF',
  }],
  ['CD', {
    code: 'CD',
    name: 'Democratic Republic of Congo',
    region: 'Africa',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 20,
    treatyPartners: ['ZA', 'BE'],
    currency: 'CDF',
  }],
  ['CG', {
    code: 'CG',
    name: 'Republic of Congo',
    region: 'Africa',
    shortTermRate: 20,
    longTermRate: 20,
    longTermThresholdDays: 0,
    dividendRate: 20,
    treatyPartners: ['FR'],
    currency: 'XAF',
  }],

  // =====================================================
  // ADDITIONAL AFRICAN COUNTRIES
  // =====================================================
  ['ML', {
    code: 'ML',
    name: 'Mali',
    region: 'Africa',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['FR'],
    currency: 'XOF',
  }],
  ['BF', {
    code: 'BF',
    name: 'Burkina Faso',
    region: 'Africa',
    shortTermRate: 15,
    longTermRate: 15,
    longTermThresholdDays: 0,
    dividendRate: 12.5,
    treatyPartners: ['FR'],
    currency: 'XOF',
  }],
  ['NE', {
    code: 'NE',
    name: 'Niger',
    region: 'Africa',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['FR'],
    currency: 'XOF',
  }],
  ['TD', {
    code: 'TD',
    name: 'Chad',
    region: 'Africa',
    shortTermRate: 20,
    longTermRate: 20,
    longTermThresholdDays: 0,
    dividendRate: 20,
    treatyPartners: ['FR'],
    currency: 'XAF',
  }],
  ['GA', {
    code: 'GA',
    name: 'Gabon',
    region: 'Africa',
    shortTermRate: 20,
    longTermRate: 20,
    longTermThresholdDays: 0,
    dividendRate: 20,
    treatyPartners: ['FR', 'BE', 'CA'],
    currency: 'XAF',
  }],
  ['GQ', {
    code: 'GQ',
    name: 'Equatorial Guinea',
    region: 'Africa',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 25,
    treatyPartners: ['ES'],
    currency: 'XAF',
  }],
  ['CF', {
    code: 'CF',
    name: 'Central African Republic',
    region: 'Africa',
    shortTermRate: 19,
    longTermRate: 19,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['FR'],
    currency: 'XAF',
  }],
  ['SS', {
    code: 'SS',
    name: 'South Sudan',
    region: 'Africa',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: [],
    currency: 'SSP',
  }],
  ['ER', {
    code: 'ER',
    name: 'Eritrea',
    region: 'Africa',
    shortTermRate: 30,
    longTermRate: 30,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: [],
    currency: 'ERN',
  }],
  ['DJ', {
    code: 'DJ',
    name: 'Djibouti',
    region: 'Africa',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['FR'],
    currency: 'DJF',
    notes: 'No income tax.',
  }],
  ['SO', {
    code: 'SO',
    name: 'Somalia',
    region: 'Africa',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: [],
    currency: 'SOS',
    notes: 'Limited tax system.',
  }],
  ['MW', {
    code: 'MW',
    name: 'Malawi',
    region: 'Africa',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['GB', 'ZA', 'NO'],
    currency: 'MWK',
    notes: 'No capital gains tax.',
  }],
  ['SZ', {
    code: 'SZ',
    name: 'Eswatini',
    region: 'Africa',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['ZA', 'GB'],
    currency: 'SZL',
    notes: 'No capital gains tax.',
  }],
  ['LS', {
    code: 'LS',
    name: 'Lesotho',
    region: 'Africa',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 25,
    treatyPartners: ['ZA', 'GB'],
    currency: 'LSL',
    notes: 'No capital gains tax.',
  }],
  ['GM', {
    code: 'GM',
    name: 'Gambia',
    region: 'Africa',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['GB'],
    currency: 'GMD',
  }],
  ['GW', {
    code: 'GW',
    name: 'Guinea-Bissau',
    region: 'Africa',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['PT'],
    currency: 'XOF',
  }],
  ['GN', {
    code: 'GN',
    name: 'Guinea',
    region: 'Africa',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['FR'],
    currency: 'GNF',
  }],
  ['SL', {
    code: 'SL',
    name: 'Sierra Leone',
    region: 'Africa',
    shortTermRate: 25,
    longTermRate: 25,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['GB'],
    currency: 'SLE',
  }],
  ['LR', {
    code: 'LR',
    name: 'Liberia',
    region: 'Africa',
    shortTermRate: 25,
    longTermRate: 25,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['DE', 'SE'],
    currency: 'LRD',
  }],
  ['TG', {
    code: 'TG',
    name: 'Togo',
    region: 'Africa',
    shortTermRate: 7,
    longTermRate: 7,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['FR'],
    currency: 'XOF',
    notes: 'Low 7% CGT.',
  }],
  ['BJ', {
    code: 'BJ',
    name: 'Benin',
    region: 'Africa',
    shortTermRate: 15,
    longTermRate: 15,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['FR'],
    currency: 'XOF',
  }],
  ['CV', {
    code: 'CV',
    name: 'Cape Verde',
    region: 'Africa',
    shortTermRate: 1,
    longTermRate: 1,
    longTermThresholdDays: 0,
    dividendRate: 20,
    treatyPartners: ['PT'],
    currency: 'CVE',
    notes: 'Low 1% CGT.',
  }],
  ['MR', {
    code: 'MR',
    name: 'Mauritania',
    region: 'Africa',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['FR'],
    currency: 'MRU',
  }],
  ['KM', {
    code: 'KM',
    name: 'Comoros',
    region: 'Africa',
    shortTermRate: 15,
    longTermRate: 15,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['FR'],
    currency: 'KMF',
  }],
  ['ST', {
    code: 'ST',
    name: 'São Tomé and Príncipe',
    region: 'Africa',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['PT'],
    currency: 'STN',
  }],

  // =====================================================
  // ADDITIONAL CARIBBEAN & CENTRAL AMERICA
  // =====================================================
  ['BZ', {
    code: 'BZ',
    name: 'Belize',
    region: 'Caribbean',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['GB'],
    currency: 'BZD',
    notes: 'No capital gains tax.',
  }],
  ['GY', {
    code: 'GY',
    name: 'Guyana',
    region: 'Caribbean',
    shortTermRate: 20,
    longTermRate: 20,
    longTermThresholdDays: 0,
    dividendRate: 20,
    treatyPartners: ['GB', 'CA'],
    currency: 'GYD',
  }],
  ['SR', {
    code: 'SR',
    name: 'Suriname',
    region: 'Caribbean',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 25,
    treatyPartners: ['NL'],
    currency: 'SRD',
    notes: 'No capital gains tax.',
  }],
  ['HT', {
    code: 'HT',
    name: 'Haiti',
    region: 'Caribbean',
    shortTermRate: 30,
    longTermRate: 30,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['FR', 'US', 'CA'],
    currency: 'HTG',
  }],
  ['CU', {
    code: 'CU',
    name: 'Cuba',
    region: 'Caribbean',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['ES', 'RU'],
    currency: 'CUP',
    notes: 'Limited private financial markets.',
  }],
  ['LC', {
    code: 'LC',
    name: 'Saint Lucia',
    region: 'Caribbean',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB'],
    currency: 'XCD',
    notes: 'No income or capital gains tax.',
  }],
  ['VC', {
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
    region: 'Caribbean',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB'],
    currency: 'XCD',
    notes: 'No capital gains tax.',
  }],
  ['GD', {
    code: 'GD',
    name: 'Grenada',
    region: 'Caribbean',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['GB'],
    currency: 'XCD',
    notes: 'No capital gains tax.',
  }],
  ['DM', {
    code: 'DM',
    name: 'Dominica',
    region: 'Caribbean',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['GB'],
    currency: 'XCD',
    notes: 'No capital gains tax.',
  }],
  ['AG', {
    code: 'AG',
    name: 'Antigua and Barbuda',
    region: 'Caribbean',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB'],
    currency: 'XCD',
    notes: 'No income or capital gains tax.',
  }],
  ['KN', {
    code: 'KN',
    name: 'Saint Kitts and Nevis',
    region: 'Caribbean',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB'],
    currency: 'XCD',
    notes: 'No income or capital gains tax. Popular for CBI.',
  }],
  ['AW', {
    code: 'AW',
    name: 'Aruba',
    region: 'Caribbean',
    shortTermRate: 25,
    longTermRate: 25,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['NL'],
    currency: 'AWG',
  }],
  ['CW', {
    code: 'CW',
    name: 'Curaçao',
    region: 'Caribbean',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['NL'],
    currency: 'ANG',
    notes: 'No capital gains tax.',
  }],
  ['TC', {
    code: 'TC',
    name: 'Turks and Caicos',
    region: 'Caribbean',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB'],
    currency: 'USD',
    notes: 'Tax haven. No income taxes.',
  }],
  ['AI', {
    code: 'AI',
    name: 'Anguilla',
    region: 'Caribbean',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB'],
    currency: 'XCD',
    notes: 'Tax haven. No income taxes.',
  }],
  ['MS', {
    code: 'MS',
    name: 'Montserrat',
    region: 'Caribbean',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB'],
    currency: 'XCD',
    notes: 'No capital gains tax.',
  }],

  // =====================================================
  // ADDITIONAL ASIA & PACIFIC
  // =====================================================
  ['MO', {
    code: 'MO',
    name: 'Macau',
    region: 'Asia-Pacific',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['CN', 'PT'],
    currency: 'MOP',
    notes: 'No capital gains tax.',
  }],
  ['NC', {
    code: 'NC',
    name: 'New Caledonia',
    region: 'Oceania',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['FR'],
    currency: 'XPF',
    notes: 'No capital gains tax.',
  }],
  ['PF', {
    code: 'PF',
    name: 'French Polynesia',
    region: 'Oceania',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['FR'],
    currency: 'XPF',
    notes: 'No capital gains tax.',
  }],
  ['TO', {
    code: 'TO',
    name: 'Tonga',
    region: 'Oceania',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['NZ', 'AU'],
    currency: 'TOP',
    notes: 'No capital gains tax.',
  }],
  ['SB', {
    code: 'SB',
    name: 'Solomon Islands',
    region: 'Oceania',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['AU', 'NZ', 'GB'],
    currency: 'SBD',
    notes: 'No capital gains tax.',
  }],
  ['NR', {
    code: 'NR',
    name: 'Nauru',
    region: 'Oceania',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['AU'],
    currency: 'AUD',
    notes: 'No income tax.',
  }],
  ['TV', {
    code: 'TV',
    name: 'Tuvalu',
    region: 'Oceania',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: [],
    currency: 'AUD',
    notes: 'No income tax.',
  }],
  ['KI', {
    code: 'KI',
    name: 'Kiribati',
    region: 'Oceania',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: [],
    currency: 'AUD',
    notes: 'No capital gains tax.',
  }],
  ['MH', {
    code: 'MH',
    name: 'Marshall Islands',
    region: 'Oceania',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['US'],
    currency: 'USD',
    notes: 'No income tax. Crypto-friendly registry.',
  }],
  ['FM', {
    code: 'FM',
    name: 'Micronesia',
    region: 'Oceania',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['US'],
    currency: 'USD',
    notes: 'No income tax.',
  }],
  ['PW', {
    code: 'PW',
    name: 'Palau',
    region: 'Oceania',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['US'],
    currency: 'USD',
    notes: 'No income tax.',
  }],
  ['TL', {
    code: 'TL',
    name: 'Timor-Leste',
    region: 'Asia-Pacific',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['AU', 'PT'],
    currency: 'USD',
  }],
  ['GU', {
    code: 'GU',
    name: 'Guam',
    region: 'Oceania',
    shortTermRate: 35,
    longTermRate: 15,
    longTermThresholdDays: 365,
    dividendRate: 20,
    treatyPartners: ['US'],
    currency: 'USD',
    notes: 'US tax code applies.',
  }],

  // =====================================================
  // ADDITIONAL EUROPEAN TERRITORIES
  // =====================================================
  ['MC', {
    code: 'MC',
    name: 'Monaco',
    region: 'Europe',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['FR'],
    currency: 'EUR',
    notes: 'No income or capital gains tax.',
  }],
  ['AD', {
    code: 'AD',
    name: 'Andorra',
    region: 'Europe',
    shortTermRate: 10,
    longTermRate: 0,
    longTermThresholdDays: 365,
    dividendRate: 0,
    cryptoSpecificRules: {
      holdingPeriodExemption: true,
      exemptionDays: 365,
    },
    treatyPartners: ['ES', 'FR', 'PT'],
    currency: 'EUR',
    notes: 'Tax-free after 1 year holding.',
  }],
  ['SM', {
    code: 'SM',
    name: 'San Marino',
    region: 'Europe',
    shortTermRate: 12,
    longTermRate: 12,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['IT'],
    currency: 'EUR',
    notes: 'No dividend tax.',
  }],
  ['LI', {
    code: 'LI',
    name: 'Liechtenstein',
    region: 'Europe',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    cryptoSpecificRules: {
      professionalTraderRules: true,
    },
    treatyPartners: ['CH', 'AT', 'DE', 'GB'],
    currency: 'CHF',
    notes: 'No capital gains tax. Blockchain-friendly.',
  }],
  ['VA', {
    code: 'VA',
    name: 'Vatican City',
    region: 'Europe',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['IT'],
    currency: 'EUR',
    notes: 'Special tax regime.',
  }],
  ['GI', {
    code: 'GI',
    name: 'Gibraltar',
    region: 'Europe',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    cryptoSpecificRules: {
      professionalTraderRules: true,
    },
    treatyPartners: ['GB'],
    currency: 'GIP',
    notes: 'No capital gains tax. DLT framework.',
  }],
  ['IM', {
    code: 'IM',
    name: 'Isle of Man',
    region: 'Europe',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB'],
    currency: 'GBP',
    notes: 'No capital gains tax.',
  }],
  ['JE', {
    code: 'JE',
    name: 'Jersey',
    region: 'Europe',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB'],
    currency: 'GBP',
    notes: 'No capital gains tax.',
  }],
  ['GG', {
    code: 'GG',
    name: 'Guernsey',
    region: 'Europe',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['GB'],
    currency: 'GBP',
    notes: 'No capital gains tax.',
  }],
  ['FO', {
    code: 'FO',
    name: 'Faroe Islands',
    region: 'Europe',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['DK', 'NO', 'IS'],
    currency: 'DKK',
    notes: 'No capital gains tax.',
  }],
  ['AX', {
    code: 'AX',
    name: 'Åland Islands',
    region: 'Europe',
    shortTermRate: 34,
    longTermRate: 34,
    longTermThresholdDays: 0,
    dividendRate: 25.5,
    treatyPartners: ['FI'],
    currency: 'EUR',
    notes: 'Finnish tax rules apply.',
  }],
  ['GL', {
    code: 'GL',
    name: 'Greenland',
    region: 'Europe',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 36,
    treatyPartners: ['DK'],
    currency: 'DKK',
    notes: 'No capital gains tax.',
  }],
  ['AL', {
    code: 'AL',
    name: 'Albania',
    region: 'Europe',
    shortTermRate: 15,
    longTermRate: 15,
    longTermThresholdDays: 0,
    dividendRate: 8,
    treatyPartners: ['IT', 'DE', 'TR', 'GR', 'CH'],
    currency: 'ALL',
  }],
  ['ME', {
    code: 'ME',
    name: 'Montenegro',
    region: 'Europe',
    shortTermRate: 9,
    longTermRate: 9,
    longTermThresholdDays: 0,
    dividendRate: 9,
    treatyPartners: ['RS', 'DE', 'AT', 'CH', 'IT'],
    currency: 'EUR',
    notes: 'Low 9% flat rate.',
  }],
  ['RS', {
    code: 'RS',
    name: 'Serbia',
    region: 'Europe',
    shortTermRate: 15,
    longTermRate: 15,
    longTermThresholdDays: 0,
    dividendRate: 15,
    treatyPartners: ['DE', 'AT', 'CH', 'IT', 'GB', 'FR', 'NL'],
    currency: 'RSD',
  }],
  ['BA', {
    code: 'BA',
    name: 'Bosnia and Herzegovina',
    region: 'Europe',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 5,
    treatyPartners: ['HR', 'RS', 'SI', 'AT', 'DE'],
    currency: 'BAM',
    notes: 'Low 10% rate.',
  }],
  ['MK', {
    code: 'MK',
    name: 'North Macedonia',
    region: 'Europe',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['DE', 'AT', 'CH', 'IT', 'NL', 'HR', 'SI', 'RS'],
    currency: 'MKD',
    notes: 'Low 10% flat rate.',
  }],
  ['XK', {
    code: 'XK',
    name: 'Kosovo',
    region: 'Europe',
    shortTermRate: 10,
    longTermRate: 10,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['DE', 'AT', 'CH', 'AL'],
    currency: 'EUR',
    notes: 'Low 10% rate. No dividend tax.',
  }],
  ['MD', {
    code: 'MD',
    name: 'Moldova',
    region: 'Europe',
    shortTermRate: 12,
    longTermRate: 12,
    longTermThresholdDays: 0,
    dividendRate: 6,
    treatyPartners: ['RO', 'DE', 'AT', 'CH', 'IT', 'PL', 'CZ', 'HU'],
    currency: 'MDL',
  }],
  ['BY', {
    code: 'BY',
    name: 'Belarus',
    region: 'Europe',
    shortTermRate: 0,
    longTermRate: 0,
    longTermThresholdDays: 0,
    dividendRate: 13,
    cryptoSpecificRules: {
      miningTaxed: false,
      stakingTaxed: false,
    },
    treatyPartners: ['RU', 'DE', 'PL', 'LT', 'LV', 'CN'],
    currency: 'BYN',
    notes: 'Crypto tax-free until 2025.',
  }],

  // =====================================================
  // ADDITIONAL MIDDLE EAST
  // =====================================================
  ['PS', {
    code: 'PS',
    name: 'Palestine',
    region: 'Middle East',
    shortTermRate: 15,
    longTermRate: 15,
    longTermThresholdDays: 0,
    dividendRate: 10,
    treatyPartners: ['JO'],
    currency: 'ILS',
  }],
  ['IR', {
    code: 'IR',
    name: 'Iran',
    region: 'Middle East',
    shortTermRate: 25,
    longTermRate: 25,
    longTermThresholdDays: 0,
    dividendRate: 0,
    treatyPartners: ['TR', 'CN', 'IN', 'PK', 'RU'],
    currency: 'IRR',
    notes: 'Crypto mining legalized.',
  }],
]);

/**
 * Get all supported jurisdictions
 */
export function getSupportedJurisdictions(): Array<{ code: string; name: string; region: string }> {
  return Array.from(JURISDICTION_RULES.values()).map((j) => ({
    code: j.code,
    name: j.name,
    region: j.region,
  }));
}

/**
 * Get jurisdiction by code
 */
export function getJurisdictionByCode(code: string): JurisdictionRules | undefined {
  return JURISDICTION_RULES.get(code);
}

/**
 * Get jurisdictions by region
 */
export function getJurisdictionsByRegion(region: string): JurisdictionRules[] {
  return Array.from(JURISDICTION_RULES.values()).filter((j) => j.region === region);
}

/**
 * Get tax-friendly jurisdictions (0% capital gains)
 */
export function getTaxFriendlyJurisdictions(): JurisdictionRules[] {
  return Array.from(JURISDICTION_RULES.values()).filter(
    (j) => j.shortTermRate === 0 && j.longTermRate === 0
  );
}

/**
 * Get jurisdictions with holding period exemptions
 */
export function getHoldingPeriodExemptionJurisdictions(): JurisdictionRules[] {
  return Array.from(JURISDICTION_RULES.values()).filter(
    (j) => j.cryptoSpecificRules?.holdingPeriodExemption
  );
}

/**
 * Get jurisdictions with treaty partners
 */
export function getJurisdictionsWithTreaty(countryCode: string): JurisdictionRules[] {
  return Array.from(JURISDICTION_RULES.values()).filter((j) =>
    j.treatyPartners.includes(countryCode)
  );
}

export default JURISDICTION_RULES;
