/**
 * AI Sentinel v1 - Type Definitions
 * Rules-based fraud detection with human-in-the-loop governance
 */

// Alert severity levels
export type AlertSeverity = 'INFO' | 'WARNING' | 'CRITICAL';

// Alert status
export type AlertStatus = 'PENDING' | 'REVIEWING' | 'RESOLVED' | 'DISMISSED' | 'ESCALATED';

// Action types that can be taken on alerts
export type AlertAction = 'DISMISS' | 'FLAG' | 'FREEZE' | 'ESCALATE' | 'CLAWBACK_PROPOSAL';

// Rule types for fraud detection
export type RuleType = 
  | 'HIGH_VELOCITY'        // >50 txs/hour from single wallet
  | 'LARGE_TRANSFER'       // >100,000 VRTY single transaction
  | 'WASH_TRADING'         // A→B→A within 24 hours
  | 'NEW_WALLET_LARGE'     // <24h old wallet + >10,000 VRTY
  | 'STRUCTURING'          // Multiple txs just below threshold
  | 'BRIDGE_ABUSE'         // Suspicious bridge patterns
  | 'CLUSTER_ACTIVITY'     // Linked wallets coordinated activity
  | 'CUSTOM';              // Custom rule

// Transaction direction
export type TransactionDirection = 'IN' | 'OUT';

/**
 * Transaction for analysis
 */
export interface AnalyzedTransaction {
  hash: string;
  from: string;
  to: string;
  amount: string;
  asset: string;
  timestamp: Date;
  direction: TransactionDirection;
  network: 'XRPL' | 'SOLANA' | 'ETHEREUM';
  metadata?: Record<string, unknown>;
}

/**
 * Alert generated by rules engine
 */
export interface SentinelAlert {
  id: string;
  ruleType: RuleType;
  ruleName: string;
  severity: AlertSeverity;
  status: AlertStatus;
  
  // Wallet(s) involved
  primaryWallet: string;
  relatedWallets: string[];
  
  // Transaction(s) that triggered alert
  triggerTransactions: string[];  // Transaction hashes
  
  // Alert details
  title: string;
  description: string;
  evidence: AlertEvidence;
  
  // Risk scoring
  riskScore: number;  // 0-100
  confidence: number; // 0-100
  
  // Timestamps
  detectedAt: Date;
  reviewedAt?: Date;
  resolvedAt?: Date;
  
  // Review information
  reviewedBy?: string;
  resolution?: string;
  actionTaken?: AlertAction;
  
  // Audit trail
  auditLog: AlertAuditEntry[];
}

/**
 * Evidence supporting an alert
 */
export interface AlertEvidence {
  // Transaction patterns
  transactionCount?: number;
  transactionVolume?: string;
  timeWindow?: string;
  
  // Wallet analysis
  walletAge?: string;
  walletBalance?: string;
  linkedWallets?: string[];
  
  // Pattern details
  patternDescription?: string;
  patternMatches?: PatternMatch[];
  
  // Raw data
  rawData?: Record<string, unknown>;
}

/**
 * Pattern match details
 */
export interface PatternMatch {
  type: string;
  description: string;
  transactions: string[];
  timestamp: Date;
}

/**
 * Audit entry for alert actions
 */
export interface AlertAuditEntry {
  action: string;
  actor: string;
  timestamp: Date;
  details?: Record<string, unknown>;
}

/**
 * Rule definition
 */
export interface RuleDefinition {
  id: string;
  type: RuleType;
  name: string;
  description: string;
  enabled: boolean;
  severity: AlertSeverity;
  
  // Rule parameters
  parameters: RuleParameters;
  
  // Thresholds
  thresholds: RuleThresholds;
}

/**
 * Rule parameters for different rule types
 */
export interface RuleParameters {
  // HIGH_VELOCITY
  maxTransactionsPerHour?: number;
  
  // LARGE_TRANSFER
  largeTransferThreshold?: string;
  
  // WASH_TRADING
  washTradingWindow?: number;  // hours
  minWashAmount?: string;
  
  // NEW_WALLET_LARGE
  newWalletAge?: number;  // hours
  newWalletThreshold?: string;
  
  // STRUCTURING
  structuringThreshold?: string;
  structuringWindow?: number;  // hours
  structuringMinCount?: number;
  
  // BRIDGE_ABUSE
  bridgeVelocityLimit?: number;
  bridgeAmountThreshold?: string;
  
  // CLUSTER_ACTIVITY
  clusterMinSize?: number;
  clusterTimeWindow?: number;  // hours
  
  // Custom parameters
  custom?: Record<string, unknown>;
}

/**
 * Rule thresholds
 */
export interface RuleThresholds {
  warningThreshold?: number;
  criticalThreshold?: number;
  riskScoreWeight?: number;
}

/**
 * Wallet profile for analysis
 */
export interface WalletProfile {
  address: string;
  network: 'XRPL' | 'SOLANA' | 'ETHEREUM';
  
  // Basic info
  firstSeen: Date;
  lastActive: Date;
  
  // Activity metrics
  totalTransactions: number;
  totalVolume: string;
  averageTransactionSize: string;
  
  // Risk metrics
  riskScore: number;
  flagCount: number;
  alertCount: number;
  
  // Linked wallets (cluster detection)
  linkedWallets: string[];
  clusterScore: number;
  
  // KYC status
  kycVerified: boolean;
  kycLevel?: string;
}

/**
 * Transaction velocity data
 */
export interface VelocityData {
  wallet: string;
  period: string;  // 'HOUR' | 'DAY' | 'WEEK'
  transactionCount: number;
  totalVolume: string;
  averageAmount: string;
  uniqueCounterparties: number;
  timestamp: Date;
}

/**
 * Sentinel configuration
 */
export interface SentinelConfig {
  enabled: boolean;
  
  // Processing settings
  batchSize: number;
  processingInterval: number;  // ms
  
  // Alert settings
  alertRetentionDays: number;
  maxPendingAlerts: number;
  
  // Notification settings
  webhookUrl?: string;
  emailRecipients?: string[];
  slackChannel?: string;
  
  // Rule settings
  rules: RuleDefinition[];
}

/**
 * Sentinel statistics
 */
export interface SentinelStats {
  totalAlerts: number;
  alertsByStatus: Record<AlertStatus, number>;
  alertsBySeverity: Record<AlertSeverity, number>;
  alertsByRule: Record<RuleType, number>;
  
  // Processing stats
  transactionsProcessed: number;
  averageProcessingTime: number;
  
  // Action stats
  actionsToday: number;
  falsePositiveRate: number;
  
  // Time range
  periodStart: Date;
  periodEnd: Date;
}

/**
 * Guardian (human reviewer) profile
 */
export interface Guardian {
  id: string;
  wallet: string;
  name: string;
  role: 'GUARDIAN' | 'ADMIN' | 'SUPER_ADMIN';
  
  // Permissions
  canDismiss: boolean;
  canFlag: boolean;
  canFreeze: boolean;
  canEscalate: boolean;
  canInitiateClawback: boolean;
  
  // Activity
  alertsReviewed: number;
  lastActive: Date;
}

/**
 * Alert filter options
 */
export interface AlertFilter {
  status?: AlertStatus[];
  severity?: AlertSeverity[];
  ruleType?: RuleType[];
  wallet?: string;
  dateFrom?: Date;
  dateTo?: Date;
  limit?: number;
  offset?: number;
}

/**
 * Alert action request
 */
export interface AlertActionRequest {
  alertId: string;
  action: AlertAction;
  guardianWallet: string;
  reason: string;
  metadata?: Record<string, unknown>;
}

/**
 * Alert action response
 */
export interface AlertActionResponse {
  success: boolean;
  alertId: string;
  action: AlertAction;
  newStatus: AlertStatus;
  timestamp: Date;
  clawbackProposalId?: string;  // If action was CLAWBACK_PROPOSAL
}
